### PR TITLE
Handling several examples

### PR DESCRIPTION
**Pull request by MarcoTrevisiol**
Added support to several examples (both on `Helpers` and `aoc.get` mix task). Upgraded deps. Slight change to embedded template.

I hope to have explained everything well-enough in the Changelog. I hope each commit is clean and focused enough, as well.

Furthermore, I am using this version myself and I found it extremely useful on days like 16 or 15 where there are several useful example or days like 21 where the example is not the first "pre code" HTML child.

### CODE REVIEW

**Comment by mathsaey** [comment]
Thank you for your pull request! I sadly don't have time for AoC this year, which is why this repo has been a bit dead. However, I'll try to look at your PR asap, though it may only happen after Christmas. I am certainly okay with the idea of supporting multiple examples, as that is a pain point I ran into myself several times.

Does your PR include examples present in part 2 of the challenge? Or does it only look at the public part of the page for now?

**Comment by MarcoTrevisiol** [comment]
I changed the mix aoc.get task so that it downloads each example it can find. I did not explicitly mentioned, but with [this commit](https://github.com/mathsaey/advent_of_code_utils/pull/44/commits/4760959c58cecd6248b1e8dd9a85a327037ee780) the private function `fetch_examples`  take a `session` argument that is passed to the request (if it is not nil), therefore one gets the example of the second part as well. Of course, one needs to invoke the task a second time, after the first part has been completed (remark: this is completely safe since existing files are skipped).

**Comment by mathsaey** [comment]
I went through the updated code and made a few changes. Most changes are quite minor. The two most significant changes are:

- I added a function `list_examples` function so that users can easily find out which example corresponds to which `n`.
- I changed `nth` to `n`, as I think it's shorter to type without loss of information.

Let me sure to know if you disagree with any of these. If you don't, I think I can merge & release this as is :smile:.

**Comment by MarcoTrevisiol** [comment]
I agree with all of your changes. Please go on and thank you for the nice work!

**Comment by mathsaey** [comment]
Thank _you_ for the contribution! I'll make one more change: I'll publish this as version 5.0, as the name change of the example files will cause people's tests to break if they don't run `mix aoc.get` before upgrading.

**Pull request merged**
